# Generated by Django 5.2.8 on 2025-11-18 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("internal_id", models.CharField(max_length=64, unique=True)),
                ("ean", models.CharField(max_length=13, unique=True)),
                ("sku", models.CharField(blank=True, max_length=64)),
                ("base_title", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=128)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "lifecycle_status",
                    models.CharField(
                        choices=[
                            ("CONCEPT", "Concept"),
                            ("ACTIVE", "Active"),
                            ("REVIEW", "Review"),
                            ("EOL", "End of life"),
                            ("DISCONTINUED", "Discontinued"),
                        ],
                        default="CONCEPT",
                        max_length=16,
                    ),
                ),
                ("eol_date", models.DateField(blank=True, null=True)),
                ("short_description", models.CharField(blank=True, max_length=512)),
                ("long_description", models.TextField(blank=True)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("seo_description", models.CharField(blank=True, max_length=512)),
                ("qa_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("qa_notes", models.TextField(blank=True)),
                ("hs_code", models.CharField(blank=True, max_length=32)),
                ("country_of_origin", models.CharField(blank=True, max_length=64)),
                ("min_stock", models.PositiveIntegerField(default=0)),
                ("target_stock_days", models.PositiveIntegerField(default=30)),
                (
                    "base_purchase_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "extra_cost_transport_per_unit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "extra_cost_customs_per_unit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "extra_cost_fulfilment_per_unit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="core.brand",
                    ),
                ),
                (
                    "labels",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="catalog.productlabel"
                    ),
                ),
            ],
            options={
                "ordering": ("base_title",),
            },
        ),
        migrations.CreateModel(
            name="ProductChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active_on_channel", models.BooleanField(default=False)),
                (
                    "channel_title_override",
                    models.CharField(blank=True, max_length=255),
                ),
                ("channel_description_override", models.TextField(blank=True)),
                (
                    "channel_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "desired_margin_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_settings",
                        to="catalog.product",
                    ),
                ),
                (
                    "sales_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_settings",
                        to="core.saleschannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product channel configuration",
                "verbose_name_plural": "Product channel configurations",
                "unique_together": {("product", "sales_channel")},
            },
        ),
    ]
