# Generated by Django 5.2.8 on 2025-11-18 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("postal_code", models.CharField(blank=True, max_length=50)),
                ("city", models.CharField(blank=True, max_length=128)),
                ("country", models.CharField(default="NL", max_length=64)),
                ("vat_number", models.CharField(blank=True, max_length=64)),
                ("iban", models.CharField(blank=True, max_length=34)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("invoice_prefix", models.CharField(default="INV", max_length=16)),
                ("invoice_next_number", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("logo_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brands",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "unique_together": {("name", "company")},
            },
        ),
        migrations.CreateModel(
            name="SalesChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BOL", "Bol.com"),
                            ("SHOPIFY", "Shopify"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("channeldock_id", models.CharField(blank=True, max_length=128)),
                (
                    "pricing_margin_target",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("pricing_notes", models.TextField(blank=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_channels",
                        to="core.brand",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_channels",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "unique_together": {("name", "company")},
            },
        ),
    ]
