# Generated by Django 5.2.8 on 2025-11-18 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=128)),
                ("last_name", models.CharField(blank=True, max_length=128)),
                ("phone", models.CharField(blank=True, max_length=64)),
                ("shipping_street", models.CharField(blank=True, max_length=255)),
                ("shipping_postal_code", models.CharField(blank=True, max_length=32)),
                ("shipping_city", models.CharField(blank=True, max_length=128)),
                ("country", models.CharField(default="NL", max_length=64)),
                ("billing_same_as_shipping", models.BooleanField(default=True)),
                ("billing_street", models.CharField(blank=True, max_length=255)),
                ("billing_postal_code", models.CharField(blank=True, max_length=32)),
                ("billing_city", models.CharField(blank=True, max_length=128)),
                (
                    "labels",
                    models.ManyToManyField(
                        blank=True, related_name="customers", to="sales.customerlabel"
                    ),
                ),
            ],
            options={
                "ordering": ("email",),
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=128, unique=True)),
                (
                    "external_channel_order_id",
                    models.CharField(blank=True, max_length=128),
                ),
                ("order_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("PROCESSING", "Processing"),
                            ("SHIPPED", "Shipped"),
                            ("CANCELLED", "Cancelled"),
                            ("RETURNED", "Returned"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NEW",
                        max_length=16,
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        choices=[("CHANNELDOCK", "ChannelDock"), ("MANUAL", "Manual")],
                        default="CHANNELDOCK",
                        max_length=16,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PAID", "Paid"),
                            ("UNPAID", "Unpaid"),
                            ("PARTIALLY_PAID", "Partially paid"),
                        ],
                        default="PAID",
                        max_length=16,
                    ),
                ),
                (
                    "total_gross",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_net",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="core.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="sales.customer",
                    ),
                ),
                (
                    "sales_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="core.saleschannel",
                    ),
                ),
            ],
            options={
                "ordering": ("-order_date",),
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ean", models.CharField(blank=True, max_length=13)),
                ("sku", models.CharField(blank=True, max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=2, default=21, max_digits=4),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
